### ISSUE TITLE
Item not added to cart

### ISSUE THREAD

**Issue by Jnaneshballal** [dhanushkt/egross#25] opened 2020-08-04 10:47 UTC

**Comment by dhanushkt** [comment] 2020-08-04 19:14
this issue is same as #26

**Comment by dhanushkt** [comment] 2020-08-04 19:17
Duplicate of #26

**Comment by dhanushkt** [comment] 2020-08-05 07:32
![Annotation 2020-08-05 130036](https://user-images.githubusercontent.com/34242050/89384513-d2dcdc80-d71b-11ea-91d0-80d094539f37.jpg)

add to list not working in view-product.php @nithin356

**Comment by dhanushkt** [comment] 2020-08-05 07:34
![Annotation 2020-08-05 130344](https://user-images.githubusercontent.com/34242050/89384723-1e8f8600-d71c-11ea-9e5c-3a804cefe361.jpg)
view product button is also not working 
it should redirect to product.php page with its ID

**Closed as completed** 2020-08-05 12:38 UTC
Labels: bug
