### ISSUE TITLE
Item added to cart is not displayed

### ISSUE THREAD

**Issue by Jnaneshballal** [dhanushkt/egross#23] opened 2020-08-04 10:22 UTC
![1596536451703142352346946479513](https://user-images.githubusercontent.com/45487173/89283157-4b836080-d66a-11ea-85a5-87fe3866aeb6.jpg)

**Comment by dhanushkt** [comment] 2020-08-04 19:18
Duplicate of #26

**Comment by dhanushkt** [comment] 2020-08-05 08:50
Fixed in 09d238d

**Closed as completed by dhanushkt** 2020-08-05 08:50 UTC
Labels: duplicate
